# Generated by Django 5.2 on 2025-04-13 12:40

import django.db.models.deletion
import mainapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yourschool", models.CharField(max_length=100, null=True)),
                ("yourcourse", models.CharField(max_length=100, null=True)),
                ("enquiry", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("course_name", models.CharField(max_length=100)),
                ("year_of_study", models.CharField(max_length=20, null=True)),
                ("sem", models.CharField(max_length=20, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="mainapp.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True, upload_to=mainapp.models.note_file_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="mainapp.unit",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["course"], name="mainapp_uni_course__94f7ea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("name", "course_name", "year_of_study")},
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["-uploaded_at"], name="mainapp_not_uploade_90ee07_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={
                ("title", "file"),
                ("title", "unit"),
                ("title", "unit", "file"),
                ("unit", "file"),
            },
        ),
    ]
