# Generated by Django 5.2 on 2025-04-13 19:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("name", "course", "year_of_study")},
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                unique=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="sem",
            field=models.CharField(
                choices=[("1", "Semester 1"), ("2", "Semester 2")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="year_of_study",
            field=models.CharField(
                choices=[
                    ("1", "1st Year"),
                    ("2", "2nd Year"),
                    ("3", "3rd Year"),
                    ("4", "4th Year"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="unit",
            name="course_name",
        ),
    ]
