# Generated by Django 5.2 on 2025-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_unit_unique_together_alter_course_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
